# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff9d3ea2c62691e8f4cc13efd417a1d845e09b5b60aaeb1f22fc6e57cb6648d4265609abb79422313f1f794be9b97caaaea79ba9ed8ee04065eef80c808204b7

test:
  secret_key_base: 703aa4bd690a7e5fcc1ffda7a00d749c94b791d394a152eff9b08db727f231239f4471ca8e9c2b2a07bc33fdff14a63c1843858d96402c91878f75cef71115b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
